/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NewsIdImport } from './routes/news/$id'
import { Route as authAuthRegisterImport } from './routes/(auth)/auth/register'
import { Route as authAuthLoginImport } from './routes/(auth)/auth/login'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const NewsIdRoute = NewsIdImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRoute,
} as any)

const authAuthRegisterRoute = authAuthRegisterImport.update({
  id: '/(auth)/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const authAuthLoginRoute = authAuthLoginImport.update({
  id: '/(auth)/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/auth/login': {
      id: '/(auth)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authAuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/auth/register': {
      id: '/(auth)/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof authAuthRegisterImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/news/$id': typeof NewsIdRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/register': typeof authAuthRegisterRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/news/$id': typeof NewsIdRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/register': typeof authAuthRegisterRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/news/$id': typeof NewsIdRoute
  '/(auth)/auth/login': typeof authAuthLoginRoute
  '/(auth)/auth/register': typeof authAuthRegisterRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/news/$id' | '/auth/login' | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/news/$id' | '/auth/login' | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/news/$id'
    | '/(auth)/auth/login'
    | '/(auth)/auth/register'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  NewsIdRoute: typeof NewsIdRoute
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthRegisterRoute: typeof authAuthRegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  NewsIdRoute: NewsIdRoute,
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthRegisterRoute: authAuthRegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/news/$id",
        "/(auth)/auth/login",
        "/(auth)/auth/register"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/news/$id": {
      "filePath": "news/$id.tsx"
    },
    "/(auth)/auth/login": {
      "filePath": "(auth)/auth/login.tsx"
    },
    "/(auth)/auth/register": {
      "filePath": "(auth)/auth/register.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
